# inspired by https://curiouscoding.nl/posts/release-flow/#avx2

# .cargo/config-portable.toml
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=x86-64-v3"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=neoverse-n1"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-cpu=apple-a14"]
